default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: order_task_development
  pool: 5
  username: order-task
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: order_task_test
  pool: 5
  username: order-task
  password: 123456

production:
  adapter: postgresql
  encoding: unicode
  database: order_task_production
  pool: 5
  username: order-task
  password: 123456  
